  theme:
    fontOrigin: googleFonts
    cdnCaching: true
    typography:
      header: "IBM Plex Mono"
      body: "IBM Plex Mono"
      code: "IBM Plex Mono"
    colors:
      lightMode:
        light: "#ffffff"
        lightgray: "#ffffff"
        gray: "#000000"
        darkgray: "#000000"
        dark: "#000000"
        secondary: "#000000"
        tertiary: "#000000"
        highlight: "rgba(0, 0, 0, 0.08)"
        textHighlight: "#ffffff"
      darkMode:
        light: "#ffffff"
        lightgray: "#ffffff"
        gray: "#000000"
        darkgray: "#000000"
        dark: "#000000"
        secondary: "#000000"
        tertiary: "#000000"
        highlight: "rgba(0, 0, 0, 0.08)"
        textHighlight: "#ffffff"
